# Generated by Django 2.0.2 on 2020-07-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20200731_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
        migrations.RemoveField(
            model_name='thread',
            name='updated',
        ),
    ]
